# Generated by Django 2.1.4 on 2019-01-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beko33', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='come2',
            name='hh',
            field=models.CharField(default='doo', max_length=50),
            preserve_default=False,
        ),
    ]
